#!/bin/sh
#
##########################################
#
# Style Guide for uname(1)
#
# SunOS < 5.0
# SunOS dolphin 4.1.2 2 sun4c
#
# SunOS >= 5.0
# SunOS shad 5.1 Generic sun4m sparc
#
# SGI Indigo
# IRIX goldfish 4.0.5F 08280217 IP20
#
# SGI Crimson
# IRIX robin 5.0 03172041 IP17 mips
#
# Digital OFS/1
# OSF1 pollock 1.2 1.2 alpha
#
# Digital Ultrix
# ULTRIX scrod 4.2 0 RISC
#
##########################################
#
# First get the ostype from uname
#
ostype=`uname -s | tr "[A-Z]" "[a-z]"`

#
# If it is sunos see if it's really solaris i.e >= SunOS 5.0
#
osrel=`uname -r | cut -c1`
if [ "$ostype" = "sunos" ]; then
   if [ $osrel -ge 5 ]; then
      ostype=solaris
   fi
fi

# 
# Tell the user what they want to know
#
echo $ostype
